FROM node:14-alpine as dependencies
WORKDIR /app
#ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm install --frozen-lockfile

#FROM node:14-alpine as builder
#WORKDIR /app
COPY ./ ./
#COPY --from=dependencies /app/node_modules ./node_modules
RUN npm run build

#FROM node:14-alpine as runner
#WORKDIR /app
ENV NODE_ENV production
#COPY --from=builder /app/public ./public
#COPY --from=builder /app/.next ./.next
#COPY --from=builder /app/node_modules ./node_modules
#COPY --from=builder /app/package.json ./package.json
EXPOSE 3000
CMD ["npm", "start"]
