

spring:

  datasource:
    url: jdbc:mysql://localhost:9411/tpf_dev
    username: root
    password: mahdi
    driver-class-name: com.mysql.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    show-sql: true
 #   properties:
  #    javax:
  #      persistance:
   #       schema-generation:
    #        create-source: metada
     #       scripts:
      #        action: create
       #       create-target: tpf_database_create.sql
  sql:
    init:
      platform: mysql
      mode: always
server:
  port: 9090

