spring:
  datasource:
    url: jdbc:mysql://localhost:3306/the_platform?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: mahdi
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
  sql:
    init:
      platform: mysql
      mode: never
  servlet:
    multipart:
      enabled: true
      max-file-size: 250MB
      max-request-size: 250MB
server:
  port: 9090
azure:
  storage:
    account-name: ###############
    account-key: ######################################
    blob-endpoint: #############################
logging.level.org.springframework.web: DEBUG
