spring:


  datasource:
<<<<<<< HEAD
    url: jdbc:mysql://localhost:3vagrant 306/the_platform?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
=======
    url: jdbc:mysql://mysqldbx/tpdb?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
>>>>>>> 2e01649d8151b8052823e16a3d8ea9abc5adb50c
    username: root
    password: root
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    show-sql: false
  sql:
    init:
      platform: mysql
      mode: never
  servlet:
    multipart:
      enabled: true
      max-file-size: 250MB
      max-request-size: 250MB
server:
  port: 8080
azure:
  storage:
    account-name: basicstorage1414
    account-key: W4/q0164K3iX7en1J3c1nWj54p7PPCOH5Rx969K7WYibgzC7VdTNIl/9qkCfJPjWZBt0Vr9fMt0eygYKAnTF2A==
    blob-endpoint: https://basicstorage1414.blob.core.windows.net/
